### PR TITLE
 add unit test for schedulers step_when

### PR DESCRIPTION
**Pull request by MrLYG**

### CODE REVIEW

**Comment by fostiropoulos** [comment]
Can we please address the different val_loss and val_dataloader cases as discussed?

**Review by fostiropoulos — CHANGES_REQUESTED** [review]
Requires additional tests

**Comment by MrLYG** [comment]
> Requires additional tests

working on

**Comment by MrLYG** [comment]
https://github.com/MrLYG/ablator/blob/758ba6e205064ba986d45f3f544fd93cee472b84/ablator/main/model/wrapper.py#LL352C1-L352C1

I confuse about that, in up code I refered, "val_loss" always in metrics.  so if the val_loss never be None whatever the val_dataloader is None or not.
Because When init the TrainMetrics in code, the TrainMetrics's object is added a `__attr__` called `__value_loss_ma__`, it's default value is `nan` 
https://github.com/MrLYG/ablator/blob/758ba6e205064ba986d45f3f544fd93cee472b84/ablator/main/model/main.py#LL458C1-L466C10

**Comment by MrLYG** [comment]
https://github.com/MrLYG/ablator/blob/758ba6e205064ba986d45f3f544fd93cee472b84/ablator/main/model/wrapper.py#LL352C1-L352C1
I can see how this might be confusing. In the code I referred to, "val_loss" is indeed always present in the metrics. Thus, if the "val_dataloader" is not None, it would be logical to assume that "val_loss" would never be None.

During the initialization of "TrainMetrics" in the code, an attribute "value_loss_ma" is indeed added to the "TrainMetrics" object, and its default value is set to "nan".
https://github.com/MrLYG/ablator/blob/758ba6e205064ba986d45f3f544fd93cee472b84/ablator/main/model/main.py#LL458C1-L466C10

and also, 
https://github.com/MrLYG/ablator/blob/758ba6e205064ba986d45f3f544fd93cee472b84/ablator/main/model/wrapper.py#LL344C26-L344C26
the `metrics` is create by to_dict() function,
this function reads the TrainMetrics's object, and access it's attr `__value_loss_ma__`.

**Review by fostiropoulos — APPROVED** [review]

**Pull request merged**
