### PR TITLE
Update documentation homepage contents

### PR DESCRIPTION
**Pull request by SeanXiaoby**
- Replaced brandings and styles
- Added social media links

### CODE REVIEW

**Comment by SeanXiaoby** [comment]
The discord link seems to be expired.

**Comment by SeanXiaoby** [comment]
A live preview can be accessed here: [https://docs.ablator.online/](https://docs.ablator.online/)

**Comment by fostiropoulos** [comment]
Updated discord link https://discord.gg/9dqThvGnUW

**Comment by SeanXiaoby** [comment]
Discord link updated. New commit pushed

**Review by fostiropoulos — APPROVED** [review]

**Pull request merged**
