### PR TITLE
add pylint to github action

### PR DESCRIPTION
**Pull request by MrLYG**
add pylint autotest to github action.

### CODE REVIEW

**Comment by fostiropoulos** [comment]
Can we please add https://github.com/readthedocs/actions

https://github.com/fostiropoulos/ablator/new/abcd?filename=.github%2Fworkflows%2Fpython-publish.yml&workflow_template=ci%2Fpython-publish

https://github.com/fostiropoulos/ablator/new/abcd?filename=.github%2Fworkflows%2Fpython-package-conda.yml&workflow_template=ci%2Fpython-package-conda

Before merging? 

I will probably need to set-up secret keys for pypi. Please let me know what you would need from me.

**Comment by MrLYG** [comment]
> Can we please add https://github.com/readthedocs/actions
> 
@fostiropoulos 
This **Action** is used to build preview documentation. However, there is an easier way to preview the documentation by using a feature from Read the Docs called '[Preview documentation from pull requests](https://docs.readthedocs.io/en/stable/pull-requests.html)'. If you want to implement this feature to automatically generate preview documentation for each change in pull requests, I recommend using the Read the Docs feature, as it is very convenient." 
Please confirm a usage, if you agree to use the readthedocs feature, I will remove the readthedocs action.

image

**Comment by MrLYG** [comment]
> 
> https://github.com/fostiropoulos/ablator/new/abcd?filename=.github%2Fworkflows%2Fpython-publish.yml&workflow_template=ci%2Fpython-publish
> 
@fostiropoulos 
For this, you need to create a new API token on PyPI and add it as a secret to your repository. The name of the secret should be PYPI_API_TOKEN.
To generate and use this secret, May be you can follow these steps:
  1.Log in to [PyPI](https://pypi.org/manage/account/token/), and create a new API token. If needed, you can assign specific project permissions for the token.
  2.Copy the generated API token.
  3.Go to the GitHub repository's "Settings" tab, then click on "Secrets" in the left-hand menu.
  4.Click the "New repository secret" button, and create a new secret. Give it a name, like PYPI_API_TOKEN, and paste the copied API token into the value field. Click "Add secret" to save.

**Comment by MrLYG** [comment]
All actions are done. There are 3 actions, which include checking the code using pylint, mypy, flake8, and pytest, as well as publishing the release package to PyPI. 
However, there are still some errors when running the 'mypy' and 'pytest' check actions.

**Review by fostiropoulos — APPROVED** [review]

**Review by fostiropoulos — CHANGES_REQUESTED** [review]
The actions should be merged to trainers branch.

**Comment by MrLYG** [comment]
> The actions should be merged to trainers branch.

Ok I will close this pr. Because the base branch of pr is `abcd`. I need to checkout a branch from trainers, and add those new codes to that branch. 
Then I will submit a new pr.

**Pull request closed without merging**
