### PR TITLE
fix conflicts between reafctor_evaluation with trainers

### PR DESCRIPTION
**Pull request by MrLYG**
fix conflicts between reafctor_evaluation with trainers

### CODE REVIEW

**Review by fostiropoulos — CHANGES_REQUESTED** [review]
The files were deleted but are still referenced in the makeline and seem useful to us, what was the reason for this change?

**Comment by MrLYG** [comment]
> The files were deleted but are still referenced in the makeline and seem useful to us, what was the reason for this change?

I change the Makefile  in the `trainers` branch which will never reference Dockerfile in `localtest` folder. 
The Makefile in `trainers` branch references Dockerfile in the project 's root directory. 
And for starttest.sh, it has already been added to the `trainers` branch.

So to fix the conflict with the `trainers` branch. I delete those files in this branch.

**Comment by fostiropoulos** [comment]
The tests are failing. Ideally we would want to first merge trainers into this branch and then this branch have the tests pass and then we merge back to trainers.

**Review by fostiropoulos — CHANGES_REQUESTED** [review]
.

**Comment by fostiropoulos** [comment]
@MrLYG what is the status of this PR?

**Comment by MrLYG** [comment]
@fostiropoulos 
This pr should be close.
This pr based on pr #81.
pr [#81](https://github.com/fostiropoulos/ablator/pull/81) has already been closed, and pr#81  should be addressed by #88.

**Pull request closed without merging**
